### ISSUE TITLE
Wrapping Up Iteration #1 TODO

### ISSUE THREAD

**Issue by jburton6** [jburton6/ChildcareManagementStudio#24]
Wrapping Up Iteration #1 TODO:

- [x] Remove the prefilled login credentials
- [x] Choose user stories for Iteration #2 and highlight on Google Doc
- [x] Post summary of completed items to Wiki
- [x] Post test report to Wiki
- [x] Post scope of next iteration to Wiki ("Initial issues for the beginning of the next iteration, which may include iteration planning and iteration modeling")
- [x] Tag final commit

**Comment by mstudar1** [comment]
We decided to leave the prefilled login credentials at this point for convenience.
